session_name: nix-config
windows:
- window_name: home
  layout: even-vertical
  shell_command_before:
    - cd ~/dotfiles
  panes:
    - nvim ./deployment/configuration.nix
    - nvim ./home/deployment/Lara.nix
- window_name: rebuild
  layout: even-vertical
  shell_command_before:
    - cd ~/dotfiles
  panes:
    - echo nixops pane
    - echo home-manager pane
   
